export interface CommissionParitaireInfo {
  code: string;
  nom: string;
}

/**
 * Répertoire complet des commissions et sous-commissions paritaires belges
 * (numéro + nom), toutes statuts confondus.
 *
 * Source : SPF Emploi, Travail et Concertation sociale — banque de données
 * officielle « Salaires minimums par (sous-)commission paritaire »
 * (https://salairesminimums.be/jc_overview.html, page « (Sous-)commissions
 * paritaires existantes », consultée le 2026-09-04).
 *
 * Cette banque de données identifie chaque commission/sous-commission par un
 * code à 7 chiffres dont, selon la page elle-même, « les commissions et
 * sous-commissions paritaires officielles sont désignées par les 5 premiers
 * chiffres. Ceux-ci sont suivis par un 6e et un 7e chiffre qui sont
 * purement destinés à un usage interne ». Seules les entrées dont les 6e/7e
 * chiffres valent "00" (donc les 5 premiers chiffres = code officiel) sont
 * reprises ici, reformatées en "NNN.NN" ; les entrées à 6e/7e chiffres non
 * nuls sont des « sous-secteurs officieux » (subdivisions internes d'une CP
 * ou sous-CP existante, pas des commissions distinctes) et ont été omises
 * volontairement. L'entrée "3000000 CONSEIL NATIONAL DU TRAVAIL" a également
 * été omise : le CNT est l'organe qui coordonne les commissions paritaires,
 * ce n'est pas lui-même une commission paritaire.
 *
 * Les CP sans régime de calcul spécifique dans ce module utilisent
 * automatiquement le barème légal général — voir
 * lib/preavis/baremes/ouvrier-pre-2014/index.ts (REGISTRE, REGISTRE_ANCIENNETE)
 * pour la liste des CP ayant une table dédiée.
 */
export const TOUTES_COMMISSIONS_PARITAIRES: CommissionParitaireInfo[] = [
  { code: "100.00", nom: "Commission paritaire auxiliaire pour ouvriers" },
  { code: "101.00", nom: "Commission nationale mixte des mines" },
  { code: "102.00", nom: "Carrières" },
  { code: "102.01", nom: "Carrières de petit granit et de calcaire à tailler de la province de Hainaut" },
  { code: "102.02", nom: "Carrières de petit granit et de calcaire à tailler des provinces de Liège et de Namur" },
  { code: "102.03", nom: "Carrières de porphyre des provinces du Brabant wallon et de Hainaut et carrières de quartzite de la province du Brabant wallon" },
  { code: "102.04", nom: "Carrières de grès et de quartzite de tout le territoire du Royaume, à l'exception des carrières de quartzite de la province du Brabant wallon" },
  { code: "102.05", nom: "Carrières de kaolin et de sable exploitées à ciel ouvert dans les provinces du Brabant wallon, de Hainaut, de Liège, de Luxembourg et de Namur" },
  { code: "102.06", nom: "Carrières de gravier et de sable exploitées à ciel ouvert dans les provinces d'Anvers, de Flandre occidentale, de Flandre orientale, de Limbourg et du Brabant flamand" },
  { code: "102.07", nom: "Carrières, cimenteries et fours à chaux de l'arrondissement administratif de Tournai" },
  { code: "102.08", nom: "Carrières et scieries de marbres de tout le territoire du Royaume" },
  { code: "102.09", nom: "Carrières de calcaire non taillé et fours à chaux, carrières de dolomies et fours à dolomies de tout le territoire du Royaume" },
  { code: "102.10", nom: "Récupération de terrils" },
  { code: "102.11", nom: "Ardoisières, carrières de coticules et pierres à rasoir des provinces du Brabant wallon, de Hainaut, de Liège, de Luxembourg et de Namur" },
  { code: "104.00", nom: "Industrie sidérurgique" },
  { code: "105.00", nom: "Métaux non ferreux" },
  { code: "106.00", nom: "Industries du ciment" },
  { code: "106.01", nom: "Fabriques de ciment" },
  { code: "106.02", nom: "Industrie du béton" },
  { code: "106.03", nom: "Fibrociment" },
  { code: "107.00", nom: "Maîtres-tailleurs, tailleuses et couturières" },
  { code: "109.00", nom: "Industrie de l'habillement et de la confection" },
  { code: "110.00", nom: "Entretien du textile" },
  { code: "111.00", nom: "Constructions métallique, mécanique et électrique" },
  { code: "112.00", nom: "Entreprises de garage" },
  { code: "113.00", nom: "Industrie céramique" },
  { code: "113.04", nom: "Tuileries" },
  { code: "114.00", nom: "Industrie des briques" },
  { code: "115.00", nom: "Industrie verrière" },
  { code: "116.00", nom: "Industrie chimique" },
  { code: "117.00", nom: "Industrie et commerce du pétrole" },
  { code: "118.00", nom: "Industrie alimentaire" },
  { code: "119.00", nom: "Commerce alimentaire" },
  { code: "120.00", nom: "Industrie textile" },
  { code: "120.01", nom: "Industrie textile de l'arrondissement administratif de Verviers" },
  { code: "120.02", nom: "Préparation du lin" },
  { code: "120.03", nom: "Fabrication et commerce de sacs en jute ou en matériaux de remplacement" },
  { code: "121.00", nom: "Nettoyage" },
  { code: "124.00", nom: "Construction" },
  { code: "125.00", nom: "Industrie du bois" },
  { code: "125.01", nom: "Exploitations forestières" },
  { code: "125.02", nom: "Scieries et industries connexes" },
  { code: "125.03", nom: "Commerce du bois" },
  { code: "126.00", nom: "Ameublement et industrie transformatrice du bois" },
  { code: "127.00", nom: "Commerce de combustibles" },
  { code: "127.02", nom: "Commerce de combustibles de la Flandre orientale" },
  { code: "128.00", nom: "Industrie des cuirs et peaux et produits de remplacement" },
  { code: "128.01", nom: "Tannerie et commerce de cuirs et peaux bruts" },
  { code: "128.02", nom: "Industrie de la chaussure, bottiers et chausseurs" },
  { code: "128.03", nom: "Maroquinerie et ganterie" },
  { code: "128.05", nom: "Sellerie, fabrication de courroies et d'articles industriels en cuir" },
  { code: "128.06", nom: "Chaussures orthopédiques" },
  { code: "129.00", nom: "Production des pâtes, papiers et cartons" },
  { code: "130.00", nom: "Imprimerie, arts graphiques et journaux" },
  { code: "132.00", nom: "Travaux techniques agricoles et horticoles" },
  { code: "133.00", nom: "Industrie des tabacs" },
  { code: "136.00", nom: "Transformation du papier et du carton" },
  { code: "139.00", nom: "Batellerie" },
  { code: "140.00", nom: "Transport et logistique" },
  { code: "140.01", nom: "Autobus et autocars" },
  { code: "140.02", nom: "Taxis" },
  { code: "140.03", nom: "Transport routier et logistique pour compte de tiers" },
  { code: "140.04", nom: "Assistance en escale dans les aéroports" },
  { code: "140.05", nom: "Déménagement" },
  { code: "142.00", nom: "Entreprises de valorisation de matières premières de récupération" },
  { code: "142.01", nom: "Récupération de métaux" },
  { code: "142.02", nom: "Récupération de chiffons" },
  { code: "142.03", nom: "Récupération du papier" },
  { code: "142.04", nom: "Récupération de produits divers" },
  { code: "143.00", nom: "Pêche maritime" },
  { code: "144.00", nom: "Agriculture" },
  { code: "145.00", nom: "Entreprises horticoles" },
  { code: "146.00", nom: "Entreprises forestières" },
  { code: "147.00", nom: "Armurerie à la main" },
  { code: "148.00", nom: "Fourrure et peau en poil" },
  { code: "148.01", nom: "Couperie de poils" },
  { code: "148.03", nom: "Fabrication industrielle et fabrication artisanale de fourrure" },
  { code: "148.05", nom: "Tanneries de peaux" },
  { code: "149.00", nom: "Secteurs connexes aux constructions métallique, mécanique et électrique" },
  { code: "149.01", nom: "Électriciens : installation et distribution" },
  { code: "149.02", nom: "Carrosserie" },
  { code: "149.03", nom: "Métaux précieux" },
  { code: "149.04", nom: "Commerce du métal" },
  { code: "152.00", nom: "Institutions subsidiées de l'enseignement libre" },
  { code: "152.01", nom: "Institutions subsidiées de l'enseignement libre de la Communauté flamande" },
  { code: "152.02", nom: "Institutions subsidiées de l'enseignement libre de la Communauté française et de la Communauté germanophone" },
  { code: "200.00", nom: "Commission paritaire auxiliaire pour employés" },
  { code: "201.00", nom: "Commerce de détail indépendant" },
  { code: "202.00", nom: "Commerce de détail alimentaire" },
  { code: "202.01", nom: "Moyennes entreprises d'alimentation" },
  { code: "203.00", nom: "Carrières de petit granit" },
  { code: "205.00", nom: "Charbonnages" },
  { code: "207.00", nom: "Industrie chimique" },
  { code: "209.00", nom: "Fabrications métalliques" },
  { code: "210.00", nom: "Sidérurgie" },
  { code: "211.00", nom: "Industrie et commerce du pétrole" },
  { code: "214.00", nom: "Industrie textile" },
  { code: "215.00", nom: "Industrie de l'habillement et de la confection" },
  { code: "216.00", nom: "Employés occupés chez les notaires" },
  { code: "217.00", nom: "Employés de casino" },
  { code: "218.00", nom: "Commission paritaire nationale auxiliaire pour employés" },
  { code: "219.00", nom: "Services et organismes de contrôle technique et d'évaluation de la conformité" },
  { code: "220.00", nom: "Industrie alimentaire" },
  { code: "221.00", nom: "Industrie papetière" },
  { code: "222.00", nom: "Transformation du papier et du carton" },
  { code: "223.00", nom: "Commission paritaire nationale des sports" },
  { code: "224.00", nom: "Métaux non ferreux" },
  { code: "225.00", nom: "Institutions de l'enseignement libre subventionné" },
  { code: "225.01", nom: "Institutions de l'enseignement libre subventionné de la Communauté flamande" },
  { code: "225.02", nom: "Institutions de l'enseignement libre subventionné de la Communauté française et de la Communauté germanophone" },
  { code: "225.03", nom: "Employés des universités libres subventionnées par la Communauté flamande" },
  { code: "225.04", nom: "Employés des universités libres subventionnées par la Communauté française" },
  { code: "226.00", nom: "Commerce international, transport et logistique" },
  { code: "227.00", nom: "Secteur audiovisuel" },
  { code: "301.00", nom: "Ports" },
  { code: "301.01", nom: "Port d'Anvers (« Nationaal Paritair Comité der Haven van Antwerpen »)" },
  { code: "301.02", nom: "Port de Gand" },
  { code: "301.03", nom: "Port de Bruxelles et de Vilvorde" },
  { code: "301.04", nom: "Ports d'Ostende et de Nieuport" },
  { code: "301.05", nom: "Ports de Zeebrugge-Bruges, d'Ostende et de Nieuport" },
  { code: "302.00", nom: "Industrie hôtelière" },
  { code: "303.00", nom: "Industrie cinématographique" },
  { code: "303.01", nom: "Production de films" },
  { code: "303.03", nom: "Exploitation de salles de cinéma" },
  { code: "304.00", nom: "Spectacle" },
  { code: "306.00", nom: "Entreprises d'assurances" },
  { code: "307.00", nom: "Entreprises de courtage et agences d'assurances" },
  { code: "308.00", nom: "Sociétés de prêts hypothécaires et de capitalisation" },
  { code: "309.00", nom: "Sociétés de bourse" },
  { code: "310.00", nom: "Banques" },
  { code: "311.00", nom: "Grandes entreprises de vente au détail" },
  { code: "312.00", nom: "Grands magasins" },
  { code: "313.00", nom: "Pharmacies et offices de tarification" },
  { code: "314.00", nom: "Coiffure et soins de beauté" },
  { code: "315.00", nom: "Aviation commerciale" },
  { code: "315.01", nom: "Maintenance technique, assistance et formation dans le secteur de l'aviation" },
  { code: "315.02", nom: "Compagnies aériennes" },
  { code: "315.03", nom: "Gestion des aéroports" },
  { code: "316.00", nom: "Marine marchande" },
  { code: "317.00", nom: "Services de gardiennage et/ou de surveillance" },
  { code: "318.00", nom: "Services des aides familiales et des aides seniors" },
  { code: "318.01", nom: "Services des aides familiales et des aides seniors de la Communauté française, de la Région wallonne et de la Communauté germanophone" },
  { code: "318.02", nom: "Services des aides familiales et des aides seniors de la Communauté flamande" },
  { code: "319.00", nom: "Établissements et services d'éducation et d'hébergement" },
  { code: "319.01", nom: "Établissements et services d'éducation et d'hébergement de la Communauté flamande" },
  { code: "319.02", nom: "Établissements et services d'éducation et d'hébergement de la Communauté française, de la Région wallonne et de la Communauté germanophone" },
  { code: "320.00", nom: "Pompes funèbres" },
  { code: "321.00", nom: "Grossistes-répartiteurs de médicaments" },
  { code: "322.00", nom: "Travail intérimaire et entreprises agréées fournissant des travaux ou services de proximité" },
  { code: "322.01", nom: "Entreprises agréées fournissant des travaux ou services de proximité" },
  { code: "323.00", nom: "Gestion d'immeubles, agents immobiliers et travailleurs domestiques" },
  { code: "324.00", nom: "Industrie et commerce du diamant" },
  { code: "325.00", nom: "Institutions publiques de crédit" },
  { code: "326.00", nom: "Industrie du gaz et de l'électricité" },
  { code: "327.00", nom: "Entreprises de travail adapté, ateliers sociaux et « maatwerkbedrijven »" },
  { code: "327.01", nom: "Secteur flamand des entreprises de travail adapté, des ateliers sociaux et des « maatwerkbedrijven »" },
  { code: "327.02", nom: "Entreprises de travail adapté subsidiées par la Commission communautaire française" },
  { code: "327.03", nom: "Entreprises de travail adapté de la Région wallonne et de la Communauté germanophone" },
  { code: "328.00", nom: "Transport urbain et régional" },
  { code: "328.01", nom: "Transport urbain et régional de la Région flamande" },
  { code: "328.02", nom: "Transport urbain et régional de la Région wallonne" },
  { code: "328.03", nom: "Transport urbain et régional de la Région de Bruxelles-Capitale" },
  { code: "329.00", nom: "Secteur socioculturel" },
  { code: "329.01", nom: "Secteur socioculturel de la Communauté flamande" },
  { code: "329.02", nom: "Secteur socioculturel de la Communauté française et germanophone et de la Région wallonne" },
  { code: "329.03", nom: "Organisations socioculturelles fédérales et bicommunautaires" },
  { code: "330.00", nom: "Établissements et services de santé" },
  { code: "331.00", nom: "Secteur flamand de l'aide sociale et des soins de santé" },
  { code: "332.00", nom: "Secteur francophone et germanophone de l'aide sociale et des soins de santé" },
  { code: "333.00", nom: "Attractions touristiques" },
  { code: "334.00", nom: "Loteries publiques" },
  { code: "335.00", nom: "Organismes sociaux" },
  { code: "336.00", nom: "Professions libérales" },
  { code: "337.00", nom: "Secteur non marchand" },
  { code: "339.00", nom: "Sociétés de logement social agréées" },
  { code: "339.01", nom: "Sociétés de logement social agréées de la Région flamande" },
  { code: "339.02", nom: "Sociétés de logement social agréées de la Région wallonne" },
  { code: "339.03", nom: "Sociétés de logement social agréées de la Région de Bruxelles-Capitale" },
  { code: "340.00", nom: "Technologies orthopédiques" },
  { code: "341.00", nom: "Intermédiation en services bancaires et d'investissement" },
];
